Check
glcanvas/android_calculator pull request #1
Opened 2018-10-23 20:01 UTC by glcanvas

первое дз

2018-10-23 21:11 UTC, lapenok-aleksej commented
382+86=0.0=1.0
что-то странное случилось..

2018-10-23 21:12 UTC, lapenok-aleksej commented
у меня на телефоне верстка для горизонтального экрана не поместилась в экран

2018-10-23 21:18 UTC, aleksej-lapenok requested changes

2018-10-23 21:18 UTC, aleksej-lapenok commented on app/src/main/java/com/example/nikita/android_calculator/MainActivity.kt
> +        val textView = findViewById<EditText>(R.id.resultText)
а как же kotlin-android-extensions?

2018-10-23 22:41 UTC, glcanvas commented
@lapenok-aleksej убрал много равно, поправил корень,  добавил synthetic, поправил верстку

2018-10-24 13:09 UTC, nikitakaberov commented
Баллы поставлены, поэтому закрою. Пусть Алексей с тобой дальше разбирается.

2018-10-24 13:09 UTC, closed without merging